### Get firewall decision
GET http://localhost:8080/api/v1/firewall/decision?srcIp=20.20.20.20&destIp=30.30.30.30

### Add rule #1
POST http://localhost:8080/api/v1/firewall/rules
Content-Type: application/json

{
  "srcStart": "20.20.20.20",
  "srcEnd": "25.25.25.25",
  "destStart": "30.30.30.30",
  "destEnd": "35.35.35.35",
  "action": "ALLOW"
}

### Add rule #2
POST http://localhost:8080/api/v1/firewall/rules
Content-Type: application/json

{
  "srcStart": "22.22.22.22",
  "srcEnd": "24.24.24.24",
  "destStart": "40.40.40.40",
  "destEnd": "45.45.45.45",
  "action": "DENY"
}

### Add rule #3
POST http://localhost:8080/api/v1/firewall/rules
Content-Type: application/json

{
  "srcStart": "22.22.22.22",
  "srcEnd": "24.24.24.24",
  "destStart": "31.31.31.31",
  "destEnd": "34.34.34.34",
  "action": "DENY"
}

###
